plugins {
    id 'com.github.node-gradle.node'
}

task build(type: NpmTask,
        group: 'node',
        dependsOn: 'npmInstall',
        description: 'Build frontend project'
    ) {
    args = ['run', 'build']
    inputs.dir '.'
    outputs.dir "../../build/resources/main"
}

task clean(type: NpmTask,
        group: 'node',
        description: 'Clean frontend project'
    ) {
    args = ['run', 'clean']
}

repositories {
    mavenLocal()
    jcenter()
}

node {
    version = '22.15.0'
    npmVersion = '11.4.2'
    download = true
}
